######################################################################
# Automatically generated by qmake (3.1) Wed Jan 31 18:06:24 2024
######################################################################

QT += widgets core gui core5compat
TEMPLATE = app
TARGET = tmc
INCLUDEPATH += . G:\\opencv4.8\\include G:\\Qt\\6.6.1\\mingw_64\\include G:\\Qt\\Tools\\mingw1120_64\\include
LIBS += -LG:\\opencv4.8\\lib -LG:\\Qt\\6.6.1\\mingw_64\\lib -LG:\\Qt\\Tools\\mingw1120_64\\lib \                 
                -lqt6core -lqt6widgets -lqt6gui -lQt6Multimedia -lQt6MultimediaWidgets \
                -lQt6Network -lQt6TextToSpeech -lqt6printsupport -lQt6Charts -lQt6DataVisualization img.res \          
                -mwindows -llibopencv_world480
                
QMAKE_CXXFLAGS += -std=c++17 -g                


# Input
HEADERS += Editor.h 

SOURCES += tmc.cpp 

RESOURCES = Editor.qrc 


